### ISSUE TITLE
Inconsistent DeviceId reported for Android Client in session query (breaks openHAB integration)

### ISSUE THREAD

**Issue by pgfeller** [jellyfin/jellyfin-sdk-kotlin#1006]
# System Environment

Server-Version: 10.9.11
Web-Version: 10.9.11
Build-Version:10.9.11

SDK Version: **1.4.7**
Client: **Jellyfin Android 2.6.2**

# Problem

Since the update from Jellyfin 10.8 to 10.9 the [openHAB](https://www.openhab.org) home automation plugin for [Jellyfin](https://github.com/openhab/openhab-addons/tree/6b411899cc5cbe2e0822b1b3939ed2a2867489e6/bundles/org.openhab.binding.jellyfin) has problems to identify and therefore properly interact with the device.

## Analysis

The reported **DeviceId** is different, after e.g. the wlan performs the nightly frequency optimization (DeviceId 93dbb268d5ccc56d vs. DeviceId 93dbb268d5ccc56d60060b7170704352b5ae2e5b2753fd3e):

```log
SDK 1.4.7

2024-10-06 01:22:58.343 [DEBUG] [verHandler] - Session: e70a28ea8d18978256387a4a7017e915, Client: Jellyfin Android, DeviceId 93dbb268d5ccc56d, deviceName Mobile 📱 von Patrik, deviceType null
2024-10-06 01:22:58.343 [DEBUG] [verHandler] - Session found for thing UID: jellyfin:client:21f6c68442b74c0e8deb0082b4c5fcd8:93dbb268d5ccc56d, ID: 93dbb268d5ccc56d (Jellyfin - 📱 Mobile A53 von Patrik): Client Jellyfin Android, DeviceId 93dbb268d5ccc56d, DeviceName Mobile 📱 von Patrik
2024-10-06 01:22:58.344 [DEBUG] [verHandler] - No active session found for thing UID: jellyfin:client:21f6c68442b74c0e8deb0082b4c5fcd8:be86f53cb877a8b7bde2a9c35d673183de2b08cb, ID: be86f53cb877a8b7bde2a9c35d673183de2b08cb, label: Jellyfin - 📺 Fire TV
--- WLAN optimization @ 3 AM
2024-10-06 04:20:37.148 [DEBUG] [verHandler] - Got 1 sessions
2024-10-06 04:20:37.148 [DEBUG] [verHandler] - Session: 82fd6f1809940527e2a0a8d97f8ab8f4, Client: Jellyfin Android, DeviceId 93dbb268d5ccc56d60060b7170704352b5ae2e5b2753fd3e, deviceName A53 von Patrik, deviceType null
2024-10-06 04:20:37.149 [DEBUG] [verHandler] - No active session found for thing UID: jellyfin:client:21f6c68442b74c0e8deb0082b4c5fcd8:93dbb268d5ccc56d, ID: 93dbb268d5ccc56d, label: Jellyfin - 📱 Mobile A53 von Patrik
2024-10-06 04:20:37.151 [DEBUG] [verHandler] - No active session found for thing UID: jellyfin:client:21f6c68442b74c0e8deb0082b4c5fcd8:be86f53cb877a8b7bde2a9c35d673183de2b08cb, ID: be86f53cb877a8b7bde2a9c35d673183de2b08cb, label: Jellyfin - 📺 Fire TV
```

As I'm not the maintainer of the integration my understanding of the code is limited, but the use of the API seems to be straight forward - and I can not see an issue there (the code worked reliably with SDK 1.4.6 and 10.8):

```java
var asyncContinuation = new SyncResponse<List<SessionInfo>>();
new SessionApi(jellyApiClient).getSessions(this.jellyApiClient.getUserId(), null, activeWithInSeconds, asyncContinuation);
```

If this is not a problem with SDK, but Jellyfin itself, please move the issue to the correct repo - thanks. Let me know if you need additional information to troubleshoot, or if you suspect that we've to use the API differently.

**Comment by nielsvanvelzen** [comment]
It's best to report issues with a specific integration to their maintainers. This SDK is just a library to communicate with Jellyfin servers and doesn't have much logic of itself. We no longer support the mentioned versions (Jellyfin 10.8 and SDK 1.4.6), our latest versions are Jellyfin 10.9.11 and SDK 1.5.5.

Session identifiers are not persistent. They can change when a user re-authenticates, the server updates, the client version changes or even when the platform the client runs on changes. This differs per-client as they all have different ways of calculating a session id.

**Comment by pgfeller** [comment]
@nielsvanvelzen 

thank you for your reply - the session id is temporary; that's clear - but the problem we see is that the DeviceId for a device changes (or to be precise - the Id starts with the same string, but contains sometimes more characters).

Anyhow - as this SDK version is no longer supported we'll need to port to 1.5.5 and check if we still have the problem ... would the Jellyfin server repo be the right place to report the issue in case we see it with SDK 1.5.5 as well?

As this version is no longer maintained I guess we can close the issue and I'll discuss with the openHAB community about an upgrade to SDK 1.5.5 ...

with kind regards,
Patrik

**Comment by nielsvanvelzen** [comment]
The device ids will also change in some clients to workaround an issue in Jellyfin server releases before 10.9.0. For example, our Android TV app uses a unique string combined with the username it signs in for.

**Comment by pgfeller** [comment]
I did not do the RTFM step - but do you know if the logic how the device identifier works is documented? E.g. can we assume a stable id for the same user on the same device? Or is the network access point, or something else also incorporated?

I'm just lazy - so if you do not know I'll check the documentation and if necessary even the source code. As to control a device with home automation we of course need a way to identify it.

**Comment by nielsvanvelzen** [comment]
For Android TV we create a DeviceInfo object using the `androidDevice` function in this SDK:

https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/fec48e1361d4f47d13101a7c99020aae77cc461b/jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/android/AndroidDevice.kt#L24-L33

We then augment is with either the user id or user name (depending on authentication method) using an extension function in the app:

https://github.com/jellyfin/jellyfin-androidtv/blob/50ad7b30b985691774f249e13c34d70e98d1578b/app/src/main/java/org/jellyfin/androidtv/util/sdk/DeviceInfoExtensions.kt#L18-L23

So unless the app data is cleared, there can be 2 possible device ids per user for this specific client.

**Comment by pgfeller** [comment]
Many thanks for the fast response and the details! With this we should be able to adjust the binding logic to handle this - and discuss the update to the current SDK.
