### ISSUE TITLE
Rename the repository to jellyfin-sdk-kotlin

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-sdk-kotlin#195]
We've had a discussion about renaming this project before. A few names came up like "jellyfin-sdk-kotlin" and "jellyfin-apiclient-kotlin".

Since the project is entirely written in Kotlin now I think it's better to not use the term "java" in the name. I'd like to start using Kotlin Multiplatform at some point which allows us to target not only the JVM but also JavaScript, WebAssembly and iOS (just to name a few).

I'd rather rename the repository before releasing 1.0.0, although this only matters for the metadata because our package and group use "org.jellyfin.apiclient".

The new readme in #193 already uses the new name 😉 

edit (2021-03-19): the initial plan (written above) was to rename to "apiclient" but we decided "sdk" makes more sense. See my comment below for the new plan.

**Comment by dkanada** [comment]
I would prefer to start migrating our ApiClient repos to the new SDK term since it would be more accurate for most of them, so I'm in agreement.

**Comment by nielsvanvelzen** [comment]
I'd prefer the SDK term but if we use that some more changes need to be made like the package in the code so it's slightly more work.

**Comment by nielsvanvelzen** [comment]
Updated proposal:

- Repository name changes to "Jellyfin Kotlin SDK", the slug will be "jellyfin-sdk-kotlin".
- The groupid and package of the project changes from "org.jellyfin.apiclient" to "org.jellyfin.sdk" - this requires some changes in CI/openapi-generator/maven.

I think this can actually help us with the apiclient migration in the ATV app since we can now use both the old and new apiclient during the migration due to the difference in the package name. So that's an added bonus!

**Comment by Maxr1998** [comment]
`jellyfin-sdk-kotlin` sounds good, let's change it to that.

**Comment by nielsvanvelzen** [comment]
The repository is now renamed. **Make sure to rename your git remote**

```
git remote set-url upstream git@github.com:jellyfin/jellyfin-sdk-kotlin.git
```
_Note: your remote might be called something else, like `origin` instead of `upstream`_

Renaming your fork is also recommended to avoid confusion.
