### ISSUE TITLE
Automatically update OpenAPI spec

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-sdk-kotlin#210]
When a new Jellyfin server version is released the OpenAPI specification is published at https://repo.jellyfin.org/releases/openapi/. Right now updating the SDK requires running the `updateApiSpecStable` gradle task to download the JSON file and run the generator to create the generated sources.

It would be amazing if we could automate this process by creating a workflow that runs every day/week/? and compares the latest stable specification with the one in the repository. If any changes are found it should update the generated sources, push it to a new branch and **create a pull request**. We can then validate this PR manually to see if everything works correctly, and make changes to it if required.

**Comment by h1dden-da3m0n** [comment]
Okay this was way easier than expected due to a [AMAZING function](https://github.com/technote-space/create-pr-action) by *technote-space* and it would end up looking something like this: https://github.com/h1dden-da3m0n/jellyfin-sdk-kotlin/pull/1
