### ISSUE TITLE
[Feature Request] log http content

### ISSUE THREAD

**Issue by xmt328** [jellyfin/jellyfin-sdk-kotlin#286]
It is not flexible to custom HttpClientConfig for now

Is it possible to support a way add more feature like log?

**Comment by nielsvanvelzen** [comment]
Do you want to log the HTTP request and response bodies?

**Comment by xmt328** [comment]
> Do you want to log the HTTP request and response bodies?

Yes

**Comment by nielsvanvelzen** [comment]
I thought about this feature and I'm not sure what the ideal implementation would be. If the SDK put request/response data in the logs it would create an security issue as there could be access tokens, api keys or even passwords in those logs. We could add an explicit toggle to enable those logs but even then a client developer could accidentally enable it in their production builds.

**Comment by nielsvanvelzen** [comment]
While I don't see this built-in right now you can actually achieve this feature quite easy. You can extend the KtorClient class and add a logging call in the request function before calling super. Then set your new class as the default using the JellyfinOptions.
