### ISSUE TITLE
Usage for sdk.version=local

### ISSUE THREAD

**Issue by Nazar78** [jellyfin/jellyfin-sdk-kotlin#294]
Hi,

I'm trying to use a local edited copy of the SDK for testing purposes. But when I changed the sdk.version in the gradle.properties from "default" to "local" in jellyfin-android, then include the SDK output library that was created, jellyfin-sdk-kotlin\jellyfin-platform-android\build\outputs\aar\jellyfin-platform-android-debug.aar, I was getting this error when debugging jellyfin-android:

```
Execution failed for task ':app:dataBindingMergeDependencyArtifactsProprietaryDebug'.
> Could not resolve all files for configuration ':app:proprietaryDebugCompileClasspath'.
   > Could not find org.jellyfin.sdk:jellyfin-platform-android:latest-SNAPSHOT.
     Required by:
         project :app

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

I'm lost at the possible solution provided. Pardon my ignorance but how do I include a local copy of jellyfin SDK for testing in jellyfin-android? Thank you in advance.

**Comment by nielsvanvelzen** [comment]
When using the "local" version you need to make sure the library is "published" to your local maven repository. You can do this by running `gradlew publishToMavenLocal` in the SDK directory.

**Comment by Nazar78** [comment]
Oh my that was it! I was trying to figure this out for few days. Thank you very much!
