### ISSUE TITLE
[Security] Workflow gradlew-validate.yaml is using vulnerable action gradle/wrapper-validation-action

### ISSUE THREAD

**Issue by qazaqstan2025** [jellyfin/jellyfin-sdk-kotlin#342]
The workflow gradlew-validate.yaml is referencing action gradle/wrapper-validation-action using references v1. However this reference is missing the commit [89eda1fdc0167f59521d2bb10767f7169fb4d018](https://github.com/gradle/wrapper-validation-action/commits/89eda1fdc0167f59521d2bb10767f7169fb4d018) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by nielsvanvelzen** [comment]
We're using the latest available version of the `wrapper-validation-action` action. (v1 points to the same commit as v1.0.4). Please remove all of our organization's repositories from your bot.
