### ISSUE TITLE
Testing with Robolectric

### ISSUE THREAD

**Issue by shalva97** [jellyfin/jellyfin-sdk-kotlin#404]
Hi, wanted to try this library and also added Robolectric.

Anyways this line returns null and the test crashes
https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/20a5a42e56014201c3222839a4d2c124fbb9917a/jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/android/AndroidDevice.kt#L11

Is Robolectric supported? anyways my usecase is that I can play around with `jellyfin-sdk-kotlin` faster than with debugging/starting random Activities with random buttons. I could try with Instrumentation test, but idk... I dont like those

**Comment by nielsvanvelzen** [comment]
You can set your own device info so the AndroidDevice is never used. When creating the SDK set the deviceInfo option like so:

```kotlin
val jellyfin = createJellyfin {
	deviceInfo = DeviceInfo("device id", "device name")
}
```
