### ISSUE TITLE
Is permission READ_EXTERNAL_STORAGE required?

### ISSUE THREAD

**Issue by jarnedemeulemeester** [jellyfin/jellyfin-sdk-kotlin#472]
First of all thank you so much for making this library, it allowed me to create [Findroid](https://github.com/jarnedemeulemeester/findroid) :smile: 

While looking at the permissions I saw that READ_EXTERNAL_STORAGE is requested.
But is this really required? I removed it from the manifest and everything still seems to work.

According to the docs this is only required when you want to read all contents from external storage and I don't think this library does that. But maybe I'm wrong.
https://developer.android.com/reference/android/Manifest.permission#READ_EXTERNAL_STORAGE

**Comment by nielsvanvelzen** [comment]
It looks like this is left-over from the previous apiclient where it was needed to store credential information. This behavior is removed now and we nog longer need the permission.
