### ISSUE TITLE
Automatically add labels to openapi update pull requests

### ISSUE THREAD

**Issue by nielsvanvelzen** [jellyfin/jellyfin-sdk-kotlin#608]
The GH actions workflow that creates the OpenAPI schema update pull requests should automatically add "enhancement" labels to the pull requests so it doesn't need to be done manually. Example PR #603.

**Comment by alialiusefi** [comment]
The github action technote-space/create-pr-action doesn't offer an out of the box solution on adding a label when createing a pr. Also, it doesnt return the result of the opened pr, such as the pr_id for me to label in the same workflow.
As an alternative, I decided to create another workflow. Hopefully this solution is ok.
