### ISSUE TITLE
Send Message is not getting received on android

### ISSUE THREAD

**Issue by hkup859** [jellyfin/jellyfin-sdk-kotlin#615]
I am new to Jellyfin and while playing around I saw the send message feature for messaging active sessions. I tried it and found that I am not seeing messages on my android. I am able to send messages from it, but not receive. No errors show on either side, it just never pops up anywhere.

**Comment by nielsvanvelzen** [comment]
How did you implement the sockets? Did you use the code from our documentation sample?

**Comment by hkup859** [comment]
I'm not familiar with what you are referring to, can you explain it in more detail? I have setup the jellyfin server using docker in unraid. It's a fairly basic setup. I send a message from the android app and it worked on my computer browser, but did not work in reverse.

**Comment by nielsvanvelzen** [comment]
You've created an issue in the repository for the Kotlin SDK, this is a development library and not a client. Please recreate your issue in the appropriate repository.

**Comment by hkup859** [comment]
My bad. I saw Android in the description and didn't think to look further. Thanks!
