### ISSUE TITLE
Reconnect behaviour

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyfin/jellyfin-sdk-kotlin#818]
**Problem**

1. I lock the phone and some services wireless or related services will idle (after a "moment").
2. After unlock and the app is open i will "redirected" to server URL screen

**Possible Solutions**

- Retry to connect to last server
- A button connect to last server

**Workaround**

1. Fore stop the app
2. Start it, uses the last server

**Comment by nielsvanvelzen** [comment]
This repository is for our Kotlin SDK and the issues are for developers only. If you have an issue with one of the apps using it you should report your issue in the repository for that app.

The Jellyfin mobile repository is at https://github.com/jellyfin/jellyfin-android
