### ISSUE TITLE
SocketInstance / ReconnectHelper can get stuck disconnected

### ISSUE THREAD

**Issue by chadkouse** [jellyfin/jellyfin-sdk-kotlin#890]
I've been investigating an [issue](https://github.com/jellyfin/jellyfin-androidtv/issues/3461) in jellyfin-androidtv where the websocket disconnects and can't be reconnected.  It appears to be related to the `attempts` in ReconnectHelper.

Our theory is that networking gets suspended once an androidtv app is in the background for a while (seems to be 15-20 min).  When this happens I can see in the logs that the websocket is trying to reconect but it can't.  After 16 reconnect attemps it just stops and there's no way to clear that `attempts` variable externally without making a new SocketInstance.  The only way `attempts` gets reset are the following:

* The socket reconnects
* There are no more listeners attached to the socket and `SocketInstance.updateConnectionState()` gets called

It would be helpful if we could reset that `attempts` counter and reconnect when the jellyfin-androidtv resumes.

Any guidance here?  Or I can just make a PR if this is the proper approach

**Comment by nielsvanvelzen** [comment]
I'm currently preparing the SDK for Jellyfin 10.9. The master branch of the SDK is currently using the 10.9 API specification so you can't just use it with the app.
We've added the WebSocket models to the OpenAPI specification so they will be automatically generated in the next release. I'm still working on some additional changes to the WebSocket code to make it simpler to use in clients, one of these changes is to use flows for the listeners. Which in Android land would run on a lifecycle. This will most likely fix the issue you're experiencing.

**Comment by chadkouse** [comment]
I will keep an eye out, thanks
