### ISSUE TITLE
Add a third party client (Homedia)

### ISSUE THREAD

**Issue by valmnt** [jellyfin/jellyfin-sdk-kotlin#937]
As mentioned [here](https://kotlin-sdk.jellyfin.org/guide/getting-started.html#third-party-clients), we can suggest third-party client if we use Jellyfin SDK Kotlin. Therefore, I have opened this issue.

# Description

To get stretch to the point, my project is a third-party native application for Jellyfin on Android TV, developed using Jetpack Compose and Clean Architecture principles.

# Purpose

The purpose of this project is to propose an alternative application for Android TV utilizing the latest Android technologies.

# Road Map

We recently released the first version with limited features, and we are continuously working to improve the UX/UI and implement new features.

# Links

[Github Repository](https://github.com/valmnt/homedia) 

[Video](https://github.com/valmnt/homedia?tab=readme-ov-file#player)

**Comment by nielsvanvelzen** [comment]
This repository is for the Kotlin SDK, it has nothing to do with the jellyfin.org website. If you want to list your client you should create a pull request towards the jellyfin.org repository,

**Comment by nielsvanvelzen** [comment]
Someone just pointed out to me that you linked to the documentation of the SDK at https://kotlin-sdk.jellyfin.org. I somehow missed that, sorry!

Feel free to open a pull request to add it to the SDK documentation, its in the docs folder of this repository.
